services:
  # Backend Application
  rib-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-at-least-32-characters}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/rib
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=rib-images
      - RUST_LOG=${RUST_LOG:-info}
      - FRONTEND_URL=http://localhost:8080
      # Discord OAuth (added)
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI:-http://localhost:8080/api/v1/auth/discord/callback}
      # Optional security / bootstrap
      - ENABLE_HSTS=${ENABLE_HSTS:-false}
      - CSP_POLICY=${CSP_POLICY}
      - BOOTSTRAP_ADMIN_DISCORD_IDS=${BOOTSTRAP_ADMIN_DISCORD_IDS}
    volumes:
      - rib-data:/app/data
    depends_on:
      - postgres
      - redis
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  # Database
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rib
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      
  # Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      
  # Object Storage
  minio:
  # Using official Docker Hub image; previous quay.io tag not found (likely removed/renamed)
  # Pin to inspected current release instead of :latest for reproducibility
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      

volumes:
  postgres-data: {}
  redis-data: {}
  minio-data: {}
  rib-data: {}
