apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

images:
  - name: ribacr123.azurecr.io/rib
    newTag: v0.1.0   # bump per release/tag

patches:
  - target:
      kind: Deployment
      name: rib-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
