apiVersion: v1
kind: ConfigMap
metadata:
  name: rib-config
  namespace: rib
  labels:
    app: rib
data:
  # Application Configuration
  RUST_LOG: "info"
  FRONTEND_URL: "http://localhost:3000"
  RIB_DATA_DIR: "/app/data"
  
  # Database Configuration
  DATABASE_URL: "postgres://postgres:postgres@postgres-service:5432/rib"
  
  # Redis Configuration  
  REDIS_URL: "redis://redis-service:6379"
  
  # MinIO S3 Configuration
  S3_ENDPOINT: "http://minio-service:9000"
  S3_BUCKET: "rib-images"
  S3_ACCESS_KEY: "minioadmin"
  
  # Discord OAuth Configuration (will be overridden by secrets if provided)
  DISCORD_REDIRECT_URI: "http://localhost:8080/api/v1/auth/discord/callback"
  
  # Security Configuration
  ENABLE_HSTS: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: rib-secrets
  namespace: rib
  labels:
    app: rib
type: Opaque
data:
  # JWT Secret (base64 encoded) - replace with your own secure secret
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1hdC1sZWFzdC0zMi1jaGFyYWN0ZXJz
  
  # MinIO Secret Key (base64 encoded)
  S3_SECRET_KEY: bWluaW9hZG1pbg==
  
  # Discord OAuth Secrets (base64 encoded, empty by default)
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  
  # Optional: Bootstrap Admin Discord IDs (base64 encoded)
  BOOTSTRAP_ADMIN_DISCORD_IDS: ""