apiVersion: v1
kind: Service
metadata:
  name: rib-backend
  namespace: rib
  labels:
    app: rib-backend
spec:
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: rib-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rib-backend
  namespace: rib
  labels:
    app: rib-backend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rib-backend
  template:
    metadata:
      labels:
        app: rib-backend
    spec:
      containers:
        - name: rib
          image: ribacr123.azurecr.io/rib:latest # overridden by kustomize/tag in overlays & CI
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rib-config
            - secretRef:
                name: rib-secrets
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-data
              mountPath: /app/data
      volumes:
        - name: app-data
          emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rib-backend
  namespace: rib
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rib-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
